In [25]:
### Libraries we will be using 
import pandas as pd 
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

In [26]:
### Data we will be using 
data = pd.read_csv('../../Datasets/predictor.csv')
data.head(5)

,Age,Gender,Weight (kg),Height (m),Max_BPM,Avg_BPM,Resting_BPM,Session_Duration (hours),Calories_Burned,Fat_Percentage,...,pct_maxHR,cal_balance,lean_mass_kg,Workout_Type_Cardio,Workout_Type_HIIT,Workout_Type_Strength,Workout_Type_Yoga,Difficulty Level_Advanced,Difficulty Level_Beginner,Difficulty Level_Intermediate
0,34.91,1,65.27,1.62,188.58,157.65,69.05,1.00,1080.90,26.800377,...,0.835985,725.10,47.777394,0,0,1,0,1,0,0
1,23.37,0,56.41,1.55,179.43,131.75,73.18,1.37,1809.91,27.655021,...,0.734270,-232.91,40.809803,0,1,0,0,0,0,1
2,33.20,0,58.98,1.67,175.04,123.95,54.96,0.91,802.26,24.320821,...,0.708124,805.74,44.635580,1,0,0,0,0,0,1
3,38.69,0,93.78,1.70,191.21,155.10,50.07,1.10,1450.79,32.813572,...,0.811150,1206.21,63.007432,0,1,0,0,1,0,0
4,45.09,1,52.42,1.88,193.58,152.88,70.84,1.08,1166.40,17.307319,...,0.789751,303.60,43.347504,0,0,1,0,1,0,0

### Train Test Split

In [27]:
SEED = 133
X = data.drop('Calories_Burned', axis = 1) ## Columns that we will be using to predict
y = data['Calories_Burned'] ## Column we will be prediciting
X_train, X_test, y_train ,y_test = train_test_split(X,y, test_size = 0.2, random_state=SEED) 
data.drop(columns=['Session_Duration (hours)'], axis = 1)

,Age,Gender,Weight (kg),Height (m),Max_BPM,Avg_BPM,Resting_BPM,Calories_Burned,Fat_Percentage,Water_Intake (liters),...,pct_maxHR,cal_balance,lean_mass_kg,Workout_Type_Cardio,Workout_Type_HIIT,Workout_Type_Strength,Workout_Type_Yoga,Difficulty Level_Advanced,Difficulty Level_Beginner,Difficulty Level_Intermediate
0,34.91,1,65.27,1.62,188.58,157.65,69.05,1080.90,26.800377,1.50,...,0.835985,725.10,47.777394,0,0,1,0,1,0,0
1,23.37,0,56.41,1.55,179.43,131.75,73.18,1809.91,27.655021,1.90,...,0.734270,-232.91,40.809803,0,1,0,0,0,0,1
2,33.20,0,58.98,1.67,175.04,123.95,54.96,802.26,24.320821,1.88,...,0.708124,805.74,44.635580,1,0,0,0,0,0,1
3,38.69,0,93.78,1.70,191.21,155.10,50.07,1450.79,32.813572,2.50,...,0.811150,1206.21,63.007432,0,1,0,0,1,0,0
4,45.09,1,52.42,1.88,193.58,152.88,70.84,1166.40,17.307319,2.91,...,0.789751,303.60,43.347504,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,46.77,0,98.31,1.90,199.20,148.18,63.72,761.61,27.505498,2.99,...,0.743876,1865.39,71.269345,0,0,1,0,1,0,0
19996,40.38,0,88.12,1.87,196.18,134.18,54.04,2303.13,26.180562,3.52,...,0.683964,173.87,65.049689,0,0,1,0,0,0,1
19997,50.31,1,46.20,1.67,163.34,157.92,61.65,1468.80,23.331802,2.81,...,0.966818,-43.80,35.420708,0,0,1,0,0,1,0
19998,52.36,1,44.30,1.62,179.27,121.23,60.88,929.75,18.985868,1.59,...,0.676243,346.25,35.889260,0,0,0,1,0,0,1
19999,29.56,1,58.63,1.61,198.07,121.74,72.05,861.84,24.435892,1.99,...,0.614631,804.16,44.303237,0,0,0,1,1,0,0

### Since our data is cleaned with proper data types and has been splitted into train and test data we can use this information to train different regressor models: including LinearRegressor, RandomForestRegressor, XGBoostRegressor and many more 

---

### Model 1: LinearRegressor

In [ ]:
### Since there are no missing values in the dataset we will proceed to the pipeline

steps = [('scalar', StandardScaler()), ('linear_model', LinearRegression())]
pipeline = Pipeline(steps)
pipeline.fit(X_train, y_train)
pipeline.predict(X_test)
y_train_pred = pipeline.predict(X_train)
y_test_pred = pipeline.predict(X_test)

r2_train = r2_score(y_train, y_train_pred) # 1.0 meaning model handles all the variance in the training data properly
r2_test = r2_score(y_test, y_test_pred) #1.0 meaning model handles all the variance properly

mse_train = mean_squared_error(y_train,y_train_pred) ## ~0 which means it has really tiny error
mse_test = mean_absolute_error(y_test, y_test_pred) ## ~0 which means it has really tiny error

### How good the model is determined by r2_trained and r2_test and mse which is basically the loss function

1.7286715689681892e-24 1.0718821386035416e-12